### ISSUE TITLE
DropdownList: BEMify classNames

### ISSUE THREAD

**Issue by mucahit** [Hipo/react-ui-toolkit#124]
Let's make the `dropdown-list-item dropdown-list__empty-message-item` className BEMified

```diff
 dropdown-list-item dropdown-list__empty-message-item
+dropdown-list__item dropdown-list__item__empty-message
```

**Comment by edizcelik** [comment]
I think it would be better if we create a DropdownListItem component and keep `dropdown-list-item` for class names. This would allow further improvement later on and it wouldn't affect the users of the component. What do you think @mucahit ?

**Comment by mucahit** [comment]
Since this is an unnecessary change I'm closing this. Thanks for the warning @edizcelik
