### ISSUE TITLE
Input crashes app on UC Browser

### ISSUE THREAD

**Issue by jamcry** [Hipo/react-ui-toolkit#176]
`getNumberSeparators` are called on every `locale` change inside `Input`. That function isn't supported in some browsers (such as mobile UCBrowser), thus causing app to crash

Sentry Error ([here](https://sentry.io/organizations/hipo/issues/2880271649/?project=5954039&query=is%3Aunresolved)) details:
> Cannot read property 'value' of undefined
> {snip} THS_SEPARATOR:e.find((function(t){return"group"===t.type})).value,DECIMAL_NUMBER_SEPARATOR:e.find((function(t){return"decimal"===t.type})).v {snip}

> user agent: Mozilla/5.0 (Linux; U; Android 11; en-US; LE2100 Build/RKQ1.201112.002) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 UCBrowser/13.4.0.1306 Mobile Safari/537.36

**Comment by yasincaliskan** [comment]
Alternative sentry issue: https://sentry.io/organizations/hipo/issues/3147060839/?project=5954039&query=getNumberSeparator&statsPeriod=90d&utc=true

**Comment by yasincaliskan** [comment]
- Let's disable localization for UCBrowser like mobile devices.
- Try to Polyfill for `Intl` API

**Comment by yasincaliskan** [comment]
Should be fixed with separated NumberInput component.
