### ISSUE TITLE
Reduce specificity within dropdown styles

### ISSUE THREAD

**Issue by edizcelik** [Hipo/react-ui-toolkit#27]
~~This selector is too specific and I think we should be able to reduce its specificity~~

```
.dropdown-container button.dropdown-header-button
```

~~Also, the `height` property is set via the height property in this block and I think we should remove that in favour of using `--button-height` variable~~  This was a mistake on my side on the project.

**Comment by mucahit** [comment]
Is this still valid? @edizcelik

**Comment by edizcelik** [comment]
What I said about `dropdown-header-button` is invalid. However, I think we can still improve the dropdown styles a bit:
`has-header-box-shadow` and `disabled` is currently nested and we can remove the nesting there by using BEM naming practices.
