### ISSUE TITLE
TypeaheadSelect: Input should stretch dynamically and come after tags

### ISSUE THREAD

**Issue by edizcelik** [Hipo/react-ui-toolkit#45]
<img width="358" alt="Screen Shot 2020-12-11 at 3 45 12 PM" src="https://user-images.githubusercontent.com/22460300/101905184-106cdd00-3bc8-11eb-8c2f-b58cc5f5f812.png">

**Comment by yasincaliskan** [comment]
I think if all options were selected, we can hide the input section. Maybe it would be better in terms of UX. What do you think? @edizcelik
